spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3307/test?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
